#!python3

lines = [
 '# this is an input file for PLoM;\n',
 "# lines starting with '#' or '*' are ignored;\n",
 "# leading ' ', '\\t', '\\n' are ignored;\n",
 '# option and value should be separated by whitespace(s) or TAB(s);\n',
 "# inline comments begin with '#'\n",
 '#########################################################################\n',
 '\n',
 '\n',
 '*** PATH OF TRAINING (INPUT) DATA ***\n',
 'training           training.txt\n',
 '\n',
 '\n',
 '*** SCALING PARAMETERS ***\n',
 'scaling            True\n',
 'scaling_method     Normalization\n',
 '# scaling_method   MinMax\n',
 '\n',
 '\n',
 '*** PCA PARAMETERS ***\n',
 '## choose one pca_method and with option that directly follows it\n',
 'pca                True\n',
 'pca_scale_evecs    True\n',
 'pca_method         cum_energy\n',
 'pca_cum_energy     0.999\n',
 '# pca_method       eigv_cutoff\n',
 '# pca_eigv_cutoff  0\n',
 '# pca_method       pca_dim\n',
 '# pca_dim          1\n',
 '\n',
 '\n',
 '*** DMAPS PARAMETERS ***\n',
 'dmaps              True\n',
 'dmaps_epsilon      auto # <float> or auto\n',
 'dmaps_kappa        1\n',
 'dmaps_L            0.1\n',
 'dmaps_first_evec   False\n',
 'dmaps_m_override   0\n',
 'dmaps_dist_method  standard\n',
 '\n',
 '\n',
 '*** SAMPLING PARAMETERS ***\n',
 'sampling           True\n',
 'num_samples        10\n',
 'parallel           False\n',
 'n_jobs             -1\n',
 'save_samples       True\n',
 'samples_fname      None # if None, file will be named using job_desc and save time\n',
 'samples_fmt        npy # npy or txt\n',
 '\n',
 '\n',
 '*** ITO PARAMETERS ***\n',
 'projection         True\n',
 'projection_source  pca # pca, scaling, or data\n',
 'projection_target  dmaps # dmaps or pca\n',
 'ito_f0             1\n',
 'ito_dr             0.1\n',
 'ito_steps          auto # <int> or auto\n',
 'ito_pot_method     3\n',
 'ito_kde_bw_factor  1\n',

 '\n',
 '\n',
 '*** JOB PARAMETERS ***\n',
 'job_desc           "2 circles"\n',
 'verbose            True\n'
 ]


with open('input_template.txt', 'w') as f:
    f.writelines(lines)